name: expandable
description: A Flutter widget that can be expanded or collapsed by clicking on a header or an icon.
version: 5.0.1

environment:
  sdk: ">=3.0.0 < 4.0.0"
  flutter: ">= 2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
